# Generated by Django 3.1.4 on 2021-03-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.TextField(default='Maharashtra'),
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='Mumbai', max_length=10),
        ),
    ]
