# Generated by Django 3.1.4 on 2021-03-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210320_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_number', models.IntegerField(max_length=16, unique=True)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('proof', models.ImageField(default='default.jpg', upload_to='proof_pics')),
                ('city', models.CharField(max_length=16)),
                ('pin_code', models.IntegerField(max_length=6)),
                ('gender', models.CharField(max_length=16)),
                ('age', models.IntegerField(default=1)),
                ('co_mobidity', models.CharField(max_length=16)),
                ('ambulance_required', models.CharField(max_length=16)),
                ('scheme', models.CharField(max_length=16)),
                ('health_centre', models.CharField(default='KEM', max_length=16)),
                ('tested', models.CharField(max_length=16)),
                ('symptoms', models.CharField(max_length=16)),
            ],
        ),
    ]
