# Generated by Django 3.1.4 on 2021-03-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_bedrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedrequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bedrequest',
            name='age',
        ),
        migrations.RemoveField(
            model_name='bedrequest',
            name='ambulance_required',
        ),
        migrations.RemoveField(
            model_name='bedrequest',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bedrequest',
            name='co_mobidity',
        ),
        migrations.RemoveField(
            model_name='bedrequest',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='bedrequest',
            name='health_centre',
        ),
        migrations.RemoveField(
            model_name='bedrequest',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='bedrequest',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='bedrequest',
            name='proof',
        ),
        migrations.RemoveField(
            model_name='bedrequest',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='bedrequest',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='bedrequest',
            name='tested',
        ),
    ]
