# Generated by Django 3.1.4 on 2021-03-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210321_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrequest',
            name='health_centre',
            field=models.CharField(default='KEM', max_length=16),
        ),
    ]
