# Generated by Django 3.1.4 on 2021-03-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210321_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrequest',
            name='aadhar_number',
            field=models.IntegerField(max_length=16),
        ),
    ]
