# Generated by Django 3.1.6 on 2021-03-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210321_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedrequest',
            name='email',
            field=models.EmailField(default='jmak0015@gmail.com', max_length=254),
        ),
    ]
