# Generated by Django 3.1.6 on 2021-03-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_bedrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(default='Andheri', max_length=10),
        ),
    ]
