# Generated by Django 3.1.4 on 2021-04-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210403_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='proof',
            field=models.ImageField(default='default.jpg', upload_to='hosp_proofs'),
        ),
    ]
