# Generated by Django 3.1.4 on 2021-04-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210403_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img1',
            field=models.ImageField(default='default.jpg', upload_to='hosp_imgs'),
        ),
        migrations.AddField(
            model_name='post',
            name='img2',
            field=models.ImageField(default='default.jpg', upload_to='hosp_imgs'),
        ),
        migrations.AddField(
            model_name='post',
            name='img3',
            field=models.ImageField(default='default.jpg', upload_to='hosp_imgs'),
        ),
        migrations.DeleteModel(
            name='Hosp_Img',
        ),
    ]
