# Generated by Django 3.1.1 on 2021-04-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210403_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='area',
            field=models.CharField(default='Andheri', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
    ]
